SC-1840: Update dependencies and modify msg field text
Allure-Security/slf4j-json-logger pull request #1
Opened 2023-03-27 17:22 UTC by ehernand

2023-03-27 19:22 UTC, sjayrams commented on mvnw
> +  echo "Warning: JAVA_HOME environment variable is not set."
exit 1?

2023-03-27 19:23 UTC, sjayrams commented on slf4j-json-logger/src/main/java/com/savoirtech/logging/slf4j/json/logger/StandardJsonLogger.java
>      try {
return this.message(message.get())?

2023-03-27 19:25 UTC, sjayrams commented on mvnw
> +#!/bin/sh
add to readme on how to use this?

2023-03-27 19:25 UTC, sjayrams approved these changes

2023-03-27 19:34 UTC, shershkop requested changes
we aren't going to import/fork outside libs. please find another way

2023-03-28 19:18 UTC, ehernand commented
Closing PR since it's not needed anymore

2023-03-28 19:18 UTC, closed without merging